In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
admissions = pd.read_csv('/content/ADMISSIONS.csv')
patients   = pd.read_csv('/content/PATIENTS.csv')
labevents  = pd.read_csv('/content/LABEVENTS.csv')
labitems   = pd.read_csv('/content/D_LABITEMS.csv')
structured = pd.read_csv('/content/structured_medical_records.csv')

print("Shapes:")
print("ADMISSIONS       :", admissions.shape)
print("PATIENTS         :", patients.shape)
print("LABEVENTS        :", labevents.shape)
print("D_LABITEMS       :", labitems.shape)
print("STRUCTURED RECORDS:", structured.shape)

Shapes:
ADMISSIONS       : (129, 19)
PATIENTS         : (100, 8)
LABEVENTS        : (76074, 9)
D_LABITEMS       : (753, 6)
STRUCTURED RECORDS: (408, 5)

### Exploring `admissions` DataFrame

In [31]:
print('First 3 rows of admissions:')
display(admissions.head(3))
print('\nShape of admissions:', admissions.shape)
print('\nColumn info for admissions:')
admissions.info()
print('\nMissing values in admissions:')
print(admissions.isnull().sum())

First 3 rows of admissions:

,row_id,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,edregtime,edouttime,diagnosis,hospital_expire_flag,has_chartevents_data
0,12258,10006,142345,2164-10-23 21:09:00,2164-11-01 17:15:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,NaN,CATHOLIC,SEPARATED,BLACK/AFRICAN AMERICAN,2164-10-23 16:43:00,2164-10-23 23:00:00,SEPSIS,0,1
1,12263,10011,105331,2126-08-14 22:32:00,2126-08-28 18:59:00,2126-08-28 18:59:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,DEAD/EXPIRED,Private,NaN,CATHOLIC,SINGLE,UNKNOWN/NOT SPECIFIED,NaN,NaN,HEPATITIS B,1,1
2,12265,10013,165520,2125-10-04 23:36:00,2125-10-07 15:13:00,2125-10-07 15:13:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,DEAD/EXPIRED,Medicare,NaN,CATHOLIC,NaN,UNKNOWN/NOT SPECIFIED,NaN,NaN,SEPSIS,1,1

Shape of admissions: (129, 19)

Column info for admissions:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129 entries, 0 to 128
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   row_id                129 non-null    int64
 1   subject_id            129 non-null    int64
 2   hadm_id               129 non-null    int64
 3   admittime             129 non-null    object
 4   dischtime             129 non-null    object
 5   deathtime             40 non-null     object
 6   admission_type        129 non-null    object
 7   admission_location    129 non-null    object
 8   discharge_location    129 non-null    object
 9   insurance             129 non-null    object
 10  language              81 non-null     object
 11  religion              128 non-null    object
 12  marital_status        113 non-null    object
 13  ethnicity             129 non-null    object
 14  edregtime             92 non-null     object
 15  edouttime             92 non-null     object
 16  diagnosis             129 non-null    object
 17  hospital_expire_flag  129 non-null    int64
 18  has_chartevents_data  129 non-null    int64
dtypes: int64(5), object(14)
memory usage: 19.3+ KB

Missing values in admissions:
row_id                   0
subject_id               0
hadm_id                  0
admittime                0
dischtime                0
deathtime               89
admission_type           0
admission_location       0
discharge_location       0
insurance                0
language                48
religion                 1
marital_status          16
ethnicity                0
edregtime               37
edouttime               37
diagnosis                0
hospital_expire_flag     0
has_chartevents_data     0
dtype: int64

### Exploring `patients` DataFrame

In [32]:
print('First 3 rows of patients:')
display(patients.head(3))
print('\nShape of patients:', patients.shape)
print('\nColumn info for patients:')
patients.info()
print('\nMissing values in patients:')
print(patients.isnull().sum())

First 3 rows of patients:

,row_id,subject_id,gender,dob,dod,dod_hosp,dod_ssn,expire_flag
0,9467,10006,F,2094-03-05 00:00:00,2165-08-12 00:00:00,2165-08-12 00:00:00,2165-08-12 00:00:00,1
1,9472,10011,F,2090-06-05 00:00:00,2126-08-28 00:00:00,2126-08-28 00:00:00,NaN,1
2,9474,10013,F,2038-09-03 00:00:00,2125-10-07 00:00:00,2125-10-07 00:00:00,2125-10-07 00:00:00,1

Shape of patients: (100, 8)

Column info for patients:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   row_id       100 non-null    int64
 1   subject_id   100 non-null    int64
 2   gender       100 non-null    object
 3   dob          100 non-null    object
 4   dod          100 non-null    object
 5   dod_hosp     70 non-null     object
 6   dod_ssn      77 non-null     object
 7   expire_flag  100 non-null    int64
dtypes: int64(3), object(5)
memory usage: 6.4+ KB

Missing values in patients:
row_id          0
subject_id      0
gender          0
dob             0
dod             0
dod_hosp       30
dod_ssn        23
expire_flag     0
dtype: int64

### Exploring `labevents` DataFrame

In [33]:
print('First 3 rows of labevents:')
display(labevents.head(3))
print('\nShape of labevents:', labevents.shape)
print('\nColumn info for labevents:')
labevents.info()
print('\nMissing values in labevents:')
print(labevents.isnull().sum())

First 3 rows of labevents:

,row_id,subject_id,hadm_id,itemid,charttime,value,valuenum,valueuom,flag
0,6244563,10006,NaN,50868,2164-09-24 20:21:00,19,19.0,mEq/L,NaN
1,6244564,10006,NaN,50882,2164-09-24 20:21:00,27,27.0,mEq/L,NaN
2,6244565,10006,NaN,50893,2164-09-24 20:21:00,10.0,10.0,mg/dL,NaN

Shape of labevents: (76074, 9)

Column info for labevents:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76074 entries, 0 to 76073
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   row_id      76074 non-null  int64
 1   subject_id  76074 non-null  int64
 2   hadm_id     61812 non-null  float64
 3   itemid      76074 non-null  int64
 4   charttime   76074 non-null  object
 5   value       76069 non-null  object
 6   valuenum    67030 non-null  float64
 7   valueuom    66669 non-null  object
 8   flag        29737 non-null  object
dtypes: float64(2), int64(3), object(4)
memory usage: 5.2+ MB

Missing values in labevents:
row_id            0
subject_id        0
hadm_id       14262
itemid            0
charttime         0
value             5
valuenum       9044
valueuom       9405
flag          46337
dtype: int64

### Exploring `labitems` DataFrame

In [34]:
print('First 3 rows of labitems:')
display(labitems.head(3))
print('\nShape of labitems:', labitems.shape)
print('\nColumn info for labitems:')
labitems.info()
print('\nMissing values in labitems:')
print(labitems.isnull().sum())

First 3 rows of labitems:

   row_id  itemid                       label  fluid   category loinc_code
0       1   50800               SPECIMEN TYPE  BLOOD  BLOOD GAS        NaN
1       2   50801  Alveolar-arterial Gradient  Blood  Blood Gas    19991-9
2       3   50802                 Base Excess  Blood  Blood Gas    11555-0

Shape of labitems: (753, 6)

Column info for labitems:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   row_id      753 non-null    int64
 1   itemid      753 non-null    int64
 2   label       753 non-null    object
 3   fluid       753 non-null    object
 4   category    753 non-null    object
 5   loinc_code  585 non-null    object
dtypes: int64(2), object(4)
memory usage: 35.4+ KB

Missing values in labitems:
row_id          0
itemid          0
label           0
fluid           0
category        0
loinc_code    168
dtype: int64

### Exploring `structured` DataFrame

In [35]:
print('First 3 rows of structured:')
display(structured.head(3))
print('\nShape of structured:', structured.shape)
print('\nColumn info for structured:')
structured.info()
print('\nMissing values in structured:')
print(structured.isnull().sum())

First 3 rows of structured:

,subject_id,hadm_id,adm_date,adm_time,medical_report
0,10076,198503,2107-03-21,17:50:00,Patient ID: 10076\n Admission Date: 2107-03...
1,10076,198503,2107-03-22,06:10:00,Patient ID: 10076\n Admission Date: 2107-03...
2,10076,198503,2107-03-23,06:45:00,Patient ID: 10076\n Admission Date: 2107-03...

Shape of structured: (408, 5)

Column info for structured:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408 entries, 0 to 407
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subject_id      408 non-null    int64
 1   hadm_id         408 non-null    int64
 2   adm_date        408 non-null    object
 3   adm_time        408 non-null    object
 4   medical_report  408 non-null    object
dtypes: int64(2), object(3)
memory usage: 16.1+ KB

Missing values in structured:
subject_id        0
hadm_id           0
adm_date          0
adm_time          0
medical_report    0
dtype: int64

### Cleaning `labevents` DataFrame

In [36]:
# Print shape before cleaning
print(f"Shape of labevents before cleaning: {labevents.shape}")

# 1. Convert CHARTTIME to datetime
labevents['charttime'] = pd.to_datetime(labevents['charttime'])

# 2. Drop rows where both VALUE and VALUENUM are null
initial_rows = labevents.shape[0]
labevents.dropna(subset=['value', 'valuenum'], how='all', inplace=True)
dropped_nulls = initial_rows - labevents.shape[0]
print(f"Dropped {dropped_nulls} rows where both 'value' and 'valuenum' were null.")

# 3. Remove duplicate rows
initial_rows = labevents.shape[0]
labevents.drop_duplicates(inplace=True)
dropped_duplicates = initial_rows - labevents.shape[0]
print(f"Dropped {dropped_duplicates} duplicate rows.")

# 4. Add a new column IS_ABNORMAL = True where FLAG column says 'abnormal'
labevents['is_abnormal'] = (labevents['flag'] == 'abnormal')

# Print shape after cleaning
print(f"Shape of labevents after cleaning: {labevents.shape}")

# Display first few rows and info after cleaning to verify
print('\nFirst 3 rows of cleaned labevents:')
display(labevents.head(3))
print('\nColumn info for cleaned labevents:')
labevents.info()

Shape of labevents before cleaning: (76074, 9)
Dropped 5 rows where both 'value' and 'valuenum' were null.
Dropped 0 duplicate rows.
Shape of labevents after cleaning: (76069, 10)

First 3 rows of cleaned labevents:

,row_id,subject_id,hadm_id,itemid,charttime,value,valuenum,valueuom,flag,is_abnormal
0,6244563,10006,NaN,50868,2164-09-24 20:21:00,19,19.0,mEq/L,NaN,False
1,6244564,10006,NaN,50882,2164-09-24 20:21:00,27,27.0,mEq/L,NaN,False
2,6244565,10006,NaN,50893,2164-09-24 20:21:00,10.0,10.0,mg/dL,NaN,False

Column info for cleaned labevents:
<class 'pandas.core.frame.DataFrame'>
Index: 76069 entries, 0 to 76073
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   row_id       76069 non-null  int64
 1   subject_id   76069 non-null  int64
 2   hadm_id      61808 non-null  float64
 3   itemid       76069 non-null  int64
 4   charttime    76069 non-null  datetime64[ns]
 5   value        76069 non-null  object
 6   valuenum     67030 non-null  float64
 7   valueuom     66668 non-null  object
 8   flag         29736 non-null  object
 9   is_abnormal  76069 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), int64(3), object(3)
memory usage: 5.9+ MB

### Cleaning `admissions` DataFrame

In [37]:
print(f"Shape of admissions before cleaning: {admissions.shape}")

# 1. Convert ADMITTIME and DISCHTIME to datetime
admissions['admittime'] = pd.to_datetime(admissions['admittime'])
admissions['dischtime'] = pd.to_datetime(admissions['dischtime'])

# 2. Calculate LOS_DAYS
admissions['los_days'] = (admissions['dischtime'] - admissions['admittime']).dt.days

# 3. Standardize text columns to uppercase (assuming all string columns should be uppercased)
for col in ['admission_type', 'admission_location', 'discharge_location', 'insurance', 'language', 'religion', 'marital_status', 'ethnicity', 'edregtime', 'edouttime', 'diagnosis']:
    if col in admissions.columns:
        admissions[col] = admissions[col].astype(str).str.upper()

print(f"Shape of admissions after cleaning: {admissions.shape}")
print('\nFirst 3 rows of cleaned admissions:')
display(admissions.head(3))
print('\nColumn info for cleaned admissions:')
admissions.info()

Shape of admissions before cleaning: (129, 19)
Shape of admissions after cleaning: (129, 20)

First 3 rows of cleaned admissions:

,row_id,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,edregtime,edouttime,diagnosis,hospital_expire_flag,has_chartevents_data,los_days
0,12258,10006,142345,2164-10-23 21:09:00,2164-11-01 17:15:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,MEDICARE,NAN,CATHOLIC,SEPARATED,BLACK/AFRICAN AMERICAN,2164-10-23 16:43:00,2164-10-23 23:00:00,SEPSIS,0,1,8
1,12263,10011,105331,2126-08-14 22:32:00,2126-08-28 18:59:00,2126-08-28 18:59:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,DEAD/EXPIRED,PRIVATE,NAN,CATHOLIC,SINGLE,UNKNOWN/NOT SPECIFIED,NAN,NAN,HEPATITIS B,1,1,13
2,12265,10013,165520,2125-10-04 23:36:00,2125-10-07 15:13:00,2125-10-07 15:13:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,DEAD/EXPIRED,MEDICARE,NAN,CATHOLIC,NAN,UNKNOWN/NOT SPECIFIED,NAN,NAN,SEPSIS,1,1,2

Column info for cleaned admissions:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129 entries, 0 to 128
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   row_id                129 non-null    int64
 1   subject_id            129 non-null    int64
 2   hadm_id               129 non-null    int64
 3   admittime             129 non-null    datetime64[ns]
 4   dischtime             129 non-null    datetime64[ns]
 5   deathtime             40 non-null     object
 6   admission_type        129 non-null    object
 7   admission_location    129 non-null    object
 8   discharge_location    129 non-null    object
 9   insurance             129 non-null    object
 10  language              129 non-null    object
 11  religion              129 non-null    object
 12  marital_status        129 non-null    object
 13  ethnicity             129 non-null    object
 14  edregtime             129 non-null    object
 15  edouttime             129 non-null    object
 16  diagnosis             129 non-null    object
 17  hospital_expire_flag  129 non-null    int64
 18  has_chartevents_data  129 non-null    int64
 19  los_days              129 non-null    int64
dtypes: datetime64[ns](2), int64(6), object(12)
memory usage: 20.3+ KB

### Cleaning `patients` DataFrame

In [38]:
print(f"Shape of patients before cleaning: {patients.shape}")

# 1. Convert DOB and DOD to datetime
patients['dob'] = pd.to_datetime(patients['dob'])
patients['dod'] = pd.to_datetime(patients['dod'])

# 2. Standardize GENDER to uppercase
patients['gender'] = patients['gender'].astype(str).str.upper()

# 3. Drop duplicates on SUBJECT_ID
initial_rows = patients.shape[0]
patients.drop_duplicates(subset=['subject_id'], inplace=True)
dropped_duplicates = initial_rows - patients.shape[0]
print(f"Dropped {dropped_duplicates} duplicate rows based on 'subject_id'.")

print(f"Shape of patients after cleaning: {patients.shape}")
print('\nFirst 3 rows of cleaned patients:')
display(patients.head(3))
print('\nColumn info for cleaned patients:')
patients.info()

Shape of patients before cleaning: (100, 8)
Dropped 0 duplicate rows based on 'subject_id'.
Shape of patients after cleaning: (100, 8)

First 3 rows of cleaned patients:

,row_id,subject_id,gender,dob,dod,dod_hosp,dod_ssn,expire_flag
0,9467,10006,F,2094-03-05,2165-08-12,2165-08-12 00:00:00,2165-08-12 00:00:00,1
1,9472,10011,F,2090-06-05,2126-08-28,2126-08-28 00:00:00,NaN,1
2,9474,10013,F,2038-09-03,2125-10-07,2125-10-07 00:00:00,2125-10-07 00:00:00,1

Column info for cleaned patients:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   row_id       100 non-null    int64
 1   subject_id   100 non-null    int64
 2   gender       100 non-null    object
 3   dob          100 non-null    datetime64[ns]
 4   dod          100 non-null    datetime64[ns]
 5   dod_hosp     70 non-null     object
 6   dod_ssn      77 non-null     object
 7   expire_flag  100 non-null    int64
dtypes: datetime64[ns](2), int64(3), object(3)
memory usage: 6.4+ KB

### Cleaning `labitems` DataFrame

In [39]:
print(f"Shape of labitems before cleaning: {labitems.shape}")

# 1. Drop duplicates on ITEMID
initial_rows = labitems.shape[0]
labitems.drop_duplicates(subset=['itemid'], inplace=True)
dropped_duplicates = initial_rows - labitems.shape[0]
print(f"Dropped {dropped_duplicates} duplicate rows based on 'itemid'.")

# 2. Strip and title-case LABEL and CATEGORY columns
for col in ['label', 'category']:
    if col in labitems.columns:
        labitems[col] = labitems[col].astype(str).str.strip().str.title()

print(f"Shape of labitems after cleaning: {labitems.shape}")
print('\nFirst 3 rows of cleaned labitems:')
display(labitems.head(3))
print('\nColumn info for cleaned labitems:')
labitems.info()

Shape of labitems before cleaning: (753, 6)
Dropped 0 duplicate rows based on 'itemid'.
Shape of labitems after cleaning: (753, 6)

First 3 rows of cleaned labitems:

   row_id  itemid                       label  fluid   category loinc_code
0       1   50800               Specimen Type  BLOOD  Blood Gas        NaN
1       2   50801  Alveolar-Arterial Gradient  Blood  Blood Gas    19991-9
2       3   50802                 Base Excess  Blood  Blood Gas    11555-0

Column info for cleaned labitems:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   row_id      753 non-null    int64
 1   itemid      753 non-null    int64
 2   label       753 non-null    object
 3   fluid       753 non-null    object
 4   category    753 non-null    object
 5   loinc_code  585 non-null    object
dtypes: int64(2), object(4)
memory usage: 35.4+ KB

### Merging DataFrames into `lab_master`

In [40]:
# Start with labevents (primary table)
cleaned_database = labevents.copy()

# Merge labitems on ITEMID (left join)
cleaned_database = pd.merge(cleaned_database, labitems[['itemid', 'label', 'category', 'fluid', 'loinc_code']],
                      on='itemid', how='left', suffixes=('_event', '_item'))

# Merge admissions on SUBJECT_ID and HADM_ID (left join)
cleaned_database = pd.merge(cleaned_database, admissions[['subject_id', 'hadm_id', 'los_days', 'admission_type']],
                      on=['subject_id', 'hadm_id'], how='left', suffixes=('_lab', '_adm'))

# Merge patients on SUBJECT_ID (left join)
cleaned_database = pd.merge(cleaned_database, patients[['subject_id', 'gender', 'dob']],
                      on='subject_id', how='left', suffixes=('_master', '_patient'))

print(f"Final shape of cleaned_database: {cleaned_database.shape}")
print("\nColumns in cleaned_database:")
for col in cleaned_database.columns:
    print(f"- {col}")

print('\nFirst 3 rows of cleaned_database:')
display(cleaned_database.head(3))

Final shape of cleaned_database: (76069, 18)

Columns in cleaned_database:
- row_id
- subject_id
- hadm_id
- itemid
- charttime
- value
- valuenum
- valueuom
- flag
- is_abnormal
- label
- category
- fluid
- loinc_code
- los_days
- admission_type
- gender
- dob

First 3 rows of cleaned_database:

,row_id,subject_id,hadm_id,itemid,charttime,value,valuenum,valueuom,flag,is_abnormal,label,category,fluid,loinc_code,los_days,admission_type,gender,dob
0,6244563,10006,NaN,50868,2164-09-24 20:21:00,19,19.0,mEq/L,NaN,False,Anion Gap,Chemistry,Blood,1863-0,NaN,NaN,F,2094-03-05
1,6244564,10006,NaN,50882,2164-09-24 20:21:00,27,27.0,mEq/L,NaN,False,Bicarbonate,Chemistry,Blood,1963-8,NaN,NaN,F,2094-03-05
2,6244565,10006,NaN,50893,2164-09-24 20:21:00,10.0,10.0,mg/dL,NaN,False,"Calcium, Total",Chemistry,Blood,2000-8,NaN,NaN,F,2094-03-05

### Final Checks and Export of `cleaned_database`

In [41]:
# 1. Print percentage of missing values per column
print("\nPercentage of missing values per column in cleaned_database (before new imputation):")
print(cleaned_database.isnull().sum() * 100 / len(cleaned_database))

# 2. Print value counts for GENDER, IS_ABNORMAL, and ADMISSION_TYPE
print("\nValue counts for GENDER:")
print(cleaned_database['gender'].value_counts(dropna=False))

print("\nValue counts for IS_ABNORMAL:")
print(cleaned_database['is_abnormal'].value_counts(dropna=False))

print("\nValue counts for ADMISSION_TYPE:")
print(cleaned_database['admission_type'].value_counts(dropna=False))

# Missing value imputation
cleaned_database['flag'].fillna('normal', inplace=True);
cleaned_database['hadm_id'].fillna(0, inplace=True);
cleaned_database['los_days'].fillna(0, inplace=True);
cleaned_database['admission_type'].fillna('UNKNOWN', inplace=True);
cleaned_database['valueuom'].fillna('not recorded', inplace=True);
# valuenum is left as NaN
cleaned_database['loinc_code'].fillna('UNASSIGNED', inplace=True);

# Print missing value counts again to confirm all are fixed
print("\nPercentage of missing values per column in cleaned_database (after imputation):")
print(cleaned_database.isnull().sum() * 100 / len(cleaned_database))

# Print "Cleaning complete " at the end
print("\nCleaning complete ")

Percentage of missing values per column in cleaned_database (before new imputation):
row_id             0.000000
subject_id         0.000000
hadm_id           18.747453
itemid             0.000000
charttime          0.000000
value              0.000000
valuenum          11.882633
valueuom          12.358517
flag              60.909175
is_abnormal        0.000000
label              0.000000
category           0.000000
fluid              0.000000
loinc_code         4.062102
los_days          18.747453
admission_type    18.747453
gender             0.000000
dob                0.000000
dtype: float64

Value counts for GENDER:
gender
F    39539
M    36530
Name: count, dtype: int64

Value counts for IS_ABNORMAL:
is_abnormal
False    46560
True     29509
Name: count, dtype: int64

Value counts for ADMISSION_TYPE:
admission_type
EMERGENCY    58155
NaN          14261
ELECTIVE      3139
URGENT         514
Name: count, dtype: int64

Percentage of missing values per column in cleaned_database (after imputation):
row_id             0.000000
subject_id         0.000000
hadm_id            0.000000
itemid             0.000000
charttime          0.000000
value              0.000000
valuenum          11.882633
valueuom           0.000000
flag               0.000000
is_abnormal        0.000000
label              0.000000
category           0.000000
fluid              0.000000
loinc_code         0.000000
los_days           0.000000
admission_type     0.000000
gender             0.000000
dob                0.000000
dtype: float64

Cleaning complete

/tmp/ipykernel_1493/2504371081.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_database['flag'].fillna('normal', inplace=True);
/tmp/ipykernel_1493/2504371081.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_database['hadm_id'].fillna(0, inplace=True);
/tmp/ipykernel_1493/2504371081.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_database['los_days'].fillna(0, inplace=True);
/tmp/ipykernel_1493/2504371081.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_database['admission_type'].fillna('UNKNOWN', inplace=True);
/tmp/ipykernel_1493/2504371081.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_database['valueuom'].fillna('not recorded', inplace=True);
/tmp/ipykernel_1493/2504371081.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_database['loinc_code'].fillna('UNASSIGNED', inplace=True);

### Further Cleaning `cleaned_database`: Imputing `valuenum` from `value`

In [42]:
# Define the mapping from 'value' to 'valuenum'
value_to_num_mapping = {
    'NORMAL': 0,
    'TRACE': 0.5,
    'OCCASIONAL': 0.5,
    '1+': 1,
    '2+': 2,
    '3+': 3,
    '4+': 4
}

# Apply the mapping where 'valuenum' is null
for text_val, num_val in value_to_num_mapping.items():
    mask = cleaned_database['valuenum'].isnull() & (cleaned_database['value'].str.upper() == text_val.upper())
    cleaned_database.loc[mask, 'valuenum'] = num_val

# Fill any remaining nulls in 'valuenum' with -1 (unknown sentinel)
cleaned_database['valuenum'].fillna(-1, inplace=True)

# Print how many are still null after mapping
print(f"\nNumber of nulls in 'valuenum' after mapping: {cleaned_database['valuenum'].isnull().sum()}")

# Print value counts of the mapped values
print("\nValue counts for 'valuenum' after mapping:")
print(cleaned_database['valuenum'].value_counts(dropna=False).sort_index())

# Export as clean_lab_master_v3.csv
output_path_v3 = '/content/clean_lab_master_v3.csv'
cleaned_database.to_csv(output_path_v3, index=False)
print(f"\ncleaned_database exported to {output_path_v3}")

print("\nFurther cleaning of valuenum complete ✅")

/tmp/ipykernel_1493/2401227199.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_database['valuenum'].fillna(-1, inplace=True)

Number of nulls in 'valuenum' after mapping: 0

Value counts for 'valuenum' after mapping:
valuenum
-29.0       1
-23.0       2
-19.0       2
-18.0       3
-17.0       6
           ..
 35200.0    1
 39000.0    1
 44333.0    1
 48000.0    1
 52950.0    1
Name: count, Length: 2398, dtype: int64

cleaned_database exported to /content/clean_lab_master_v3.csv

Further cleaning of valuenum complete ✅

In [43]:
from google.colab import files

# Path to the cleaned file
output_path_v3 = '/content/clean_lab_master_v3.csv'

# Download the file
files.download(output_path_v3)